# .github/workflows/add-release-team.yml
name: Add Release Team on Release PRs

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  add_release_team:
    if: startsWith(github.event.pull_request.base.ref, 'Release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              pull_number: pr.number,
              team_reviewers: ['your-org/release-team']
            });